# If not running interactively, don't do anything
[[ $- != *i* ]] && return

autoload -U compinit && compinit -u

HISTFILE=~/.zsh_history
HISTSIZE=2000
SAVEHIST=2000
setopt appendhistory
setopt histignoredups
setopt histignorespace

alias ls='ls -phlatS --color=auto'
alias grep='grep --color=auto'

setopt PROMPT_SUBST
PROMPT=' %B%~%b %F{green}$%f '

bindkey "^[[3~" delete-char
bindkey '^[[1;5D' backward-word
bindkey '^[[1;5C' forward-word
