" Run this bash script if your Shift+Tab unindent gets screwed up by YouCompleteMe.
"
" #!/bin/bash
" YCMPATH=~/.vim/bundle/YouCompleteMe;
" [[ ! -d $YCMPATH ]] && echo $YCMPATH does not exist.;
" [[ -d $YCMPATH && -z `grep 'inoremap <S-Tab> <C-d>' $YCMPATH/autoload/youcompleteme.vim` ]] \
"   && sed \
"     -i ':a;N;$!ba;s/\(inoremap.*StopCompletion.*\n.*\n\)/\1  inoremap <S-Tab> <C-d>\n/m' \
"     $YCMPATH/autoload/youcompleteme.vim;

set nocompatible              " be iMproved, required
filetype off                  " required
" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.git
call vundle#begin()
" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'
Plugin 'Valloric/YouCompleteMe'
" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required

call plug#begin()
Plug 'mg979/vim-visual-multi'
call plug#end()

function! ToggleComment()
  let pos=getpos(".")
  let win=winsaveview()
  if getline(".") =~ '^\s*\/\/'
    normal! ^2x
    let pos[1]+=1
  else
    normal! 0i//
    let pos[1]+=1
  endif
  call winrestview(win)
  call setpos(".",pos)
endfunction

autocmd ColorScheme * hi EndOfBuffer ctermfg=3 ctermbg=none
  \ | hi Normal ctermbg=none
  \ | hi VertSplit ctermbg=none
  \ | hi EndOfBuffer ctermfg=black
  \ | hi Pmenu ctermbg=8 ctermfg=white
  \ | hi PmenuSel ctermfg=15 ctermbg=red
  \ | hi StatusLine ctermbg=3
  \ | hi StatusLineNC ctermbg=none ctermfg=white
  \ | hi CursorLine ctermbg=3 ctermfg=black
  \ | hi Folded ctermbg=none ctermfg=3

:let g:netrw_altv=1
:set number
:set nowrap
:set whichwrap+=<,>,[,]
:set backspace=indent,eol,start
:set fillchars=vert:\│
:colorscheme github
:syntax on
:syntax sync minlines=10000
:au BufReadPost *.xm set syntax=objc
:nnoremap ÷ <Esc>:call ToggleComment()<CR>i
:inoremap ÷ <Esc>:call ToggleComment()<CR>i
:nnoremap <c-Up> 10<Up>
:vnoremap <c-Up> 10<Up>
:inoremap <c-Up> <Up><Up><Up><Up><Up><Up><Up><Up><Up><Up>
:nnoremap <c-Down> 10<Down>
:vnoremap <c-Down> 10<Down>
:inoremap <c-Down> <Down><Down><Down><Down><Down><Down><Down><Down><Down><Down>
:nnoremap +2c8734ncty234hut3c4 10<Down>
:vnoremap +2c8734ncty234hut3c4 10<Down>
:inoremap +2c8734ncty234hut3c4 <Down><Down><Down><Down><Down><Down><Down><Down><Down><Down>
:nnoremap <silent><c-x> :q<cr>
:nnoremap <silent><c-s> :<c-u>update<cr>
:vnoremap <silent><c-s> <c-c>:update<cr>gv
:inoremap <silent><c-s> <c-o>:update<cr>
:set mouse=a
:set tabstop=4
:set shiftwidth=4
":set expandtab
:set autoindent
:nnoremap <S-Tab> <<
:vnoremap <S-Tab> <<<Esc>
:inoremap <S-Tab> <C-d>
:nnoremap <Tab> >>
:vnoremap <Tab> >><Esc>
:inoremap " ""<Left>
:inoremap ' ''<Left>
:inoremap ` ``<Left>
:inoremap ( ()<Left>
:inoremap { {}<Left>
:inoremap [ []<Left>
:inoremap < <><Left>
:inoremap ; <End>;
:nnoremap ; i<End>;
:vnoremap ; <Esc>i<End>;
:inoremap +; ;
:inoremap +@interface @interface<Space><Enter><Enter>@end<Up><Left>
:inoremap +@implementation @implementation<Space><Enter><Enter>@end<Up><Left>
:inoremap +%hook %hook<Space><Enter><Enter>%end<Up><Left>
:inoremap +UIAlertView UIAlertView<Space>*<Space>alert<Space>=<Space>[[UIAlertView alloc]<Enter><Tab>initWithTitle:@""<Enter>message:@""<Enter>delegate:nil<Enter>cancelButtonTitle:@"OK"<Enter>otherButtonTitles:nil];<Enter><Backspace><Backspace>[alert<Space>show];
:inoremap +NSLog NSLog(@"abla<Space>---<Space>%@",<Space>@"");<Left><Left><Left>
:inoremap +NSRegularExpression NSRegularExpression<Space>*<Space>regexp<Space>=<Space>[NSRegularExpression<Enter><Tab>regularExpressionWithPattern:@""<Enter>options:NSRegularExpressionCaseInsensitive<Enter>error:nil];<Enter><Backspace><Backspace>str<Space>=<Space>[regexp<Enter><Tab>stringByReplacingMatchesInString:str<Enter>options:0<Enter>range:NSMakeRange(0,<Space>[str length])<Enter>withTemplate:@""];<Up><Up><Up><Up><Up><Up><Up><End><Left>
:inoremap +@try @try<Space>{<Enter><Enter>}<Space>@catch(NSException<Space>*<Space>err)<Space>{<Enter><Tab>NSLog(@"abla<Space>%@<Space>%@",<Space>err.name,<Space>err.reason);<Enter><Backspace><Backspace>}
:inoremap +dispatch_async dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT,<Space>0),<Space>^(void){<Enter><Tab><Enter><Backspace><Backspace>});<Up><End>
:inoremap +dispatch_once static<Space>dispatch_once_t<Space>onceToken;<Enter>dispatch_once(&onceToken,<Space>^{<Enter><Tab><Enter><Backspace><Backspace>});<Up><End>
:inoremap +dispatch_semaphore dispatch_semaphore_t<Space>semaphore<Space>=<Space>dispatch_semaphore_create(0);<Enter>dispatch_semaphore_signal(semaphore);<Enter>if<Space>(![NSThread<Space>isMainThread])<Space>{<Enter><Tab>dispatch_semaphore_wait(semaphore,<Space>DISPATCH_TIME_FOREVER);<Enter><Backspace><Backspace>}<Space>else<Space>{<Enter><Tab>while<Space>(dispatch_semaphore_wait(semaphore,<Space>DISPATCH_TIME_NOW))<Space>{<Enter><Tab>[[NSRunLoop<Space>currentRunLoop]<Enter><Tab>runMode:NSDefaultRunLoopMode<Enter>beforeDate:[NSDate<Space>dateWithTimeIntervalSinceNow:0]];<Enter><Backspace><Backspace><Backspace><Backspace>}<Enter><Backspace><Backspace>}

set fillchars+=vert:\ 

let g:netrw_liststyle=3
let g:netrw_banner=0
